# Generated by Django 3.2.3 on 2023-01-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_phone_number',
        ),
    ]
