# Generated by Django 3.2.3 on 2022-08-27 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problembank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='شماره')),
                ('open_cost', models.IntegerField(default=5000, verbose_name='هزینه باز کردن جعبه')),
                ('reward', models.IntegerField(default=0, verbose_name='جایزه باز کردن جعبه')),
            ],
        ),
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('outcome_amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('floating_mode', models.BooleanField(default=True)),
                ('problem_cost', models.IntegerField(default=100)),
                ('easy_problem_reward', models.IntegerField(default=300)),
                ('medium_problem_reward', models.IntegerField(default=400)),
                ('hard_problem_reward', models.IntegerField(default=500)),
                ('so_hard_problem_reward', models.IntegerField(default=600)),
                ('max_room_number', models.IntegerField(default=5)),
                ('last_room_cost', models.IntegerField(default=900)),
                ('max_not_submitted_problems', models.IntegerField(default=2)),
                ('last_room_name', models.CharField(default='', max_length=128)),
                ('carrousel_win_ratio_reward', models.IntegerField(default=1.5)),
                ('carrousel_lose_ratio_reward', models.IntegerField(default=0.5)),
                ('max_time_to_play', models.FloatField(default=14400)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_cost', models.IntegerField(default=0, verbose_name='هزینه ورود به اتاق')),
                ('problem_groups', models.ManyToManyField(to='problembank.ProblemGroup', verbose_name='گروه\u200cمسئله\u200cها')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('coin', models.IntegerField(default=700, verbose_name='پول')),
                ('chat_room', models.URLField(blank=True, max_length=100, null=True, verbose_name='اتاق قرار')),
                ('carrousel_turn', models.IntegerField(default=5, verbose_name='تعداد دفعات باقی مانده چرخاندن گردونه')),
                ('first_entrance', models.FloatField(blank=True, null=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_room', to='Game2.room')),
                ('group_problems', models.ManyToManyField(related_name='team', to='problembank.ProblemGroup')),
                ('users', models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_room', to='Game2.room')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_room', to='Game2.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_box', to='Game2.box')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_box', to='Game2.team')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=200, null=True)),
                ('has_seen', models.BooleanField(default=False)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
