# Generated by Django 3.2.3 on 2022-08-26 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problembank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='شماره')),
                ('open_cost', models.IntegerField(default=0, verbose_name='هزینه باز کردن جعبه')),
                ('reward', models.IntegerField(default=0, verbose_name='جایزه باز کردن جعبه')),
            ],
        ),
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('outcome_amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_cost', models.IntegerField(default=0, verbose_name='هزینه ورود به اتاق')),
                ('problem_groups', models.ManyToManyField(to='problembank.ProblemGroup', verbose_name='گروه\u200cمسئله\u200cها')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('coin', models.IntegerField(default=700, verbose_name='پول')),
                ('chat_room', models.URLField(blank=True, max_length=100, null=True, verbose_name='اتاق قرار')),
                ('carrousel_turn', models.IntegerField(default=5, verbose_name='تعداد دفعات باقی مانده چرخاندن گردونه')),
                ('current_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_room', to='Game2.room')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_room', to='Game2.room')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_room', to='Game2.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_box', to='Game2.box')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_box', to='Game2.team')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=200, null=True)),
                ('has_seen', models.BooleanField(default=False)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='Game2.team')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.CharField(choices=[('NOT_ANSWERED', 'Not Answered'), ('ANSWERED', 'Answered'), ('SCORED', 'Scored')], default='NOT_ANSWERED', max_length=20)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('mark', models.IntegerField(default=0)),
                ('group_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_problem', to='problembank.problemgroup')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='problembank.problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='Game2.team')),
            ],
        ),
    ]
