# Generated by Django 3.2.3 on 2022-08-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='carrousel_lose_ratio_reward',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='carrousel_win_ratio_reward',
            field=models.FloatField(default=1.5),
        ),
    ]
