# Generated by Django 3.2.3 on 2022-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='floating_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_entrance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
