# Generated by Django 3.2.3 on 2022-08-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0010_auto_20220826_1041'),
        ('Game2', '0002_auto_20220826_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='group_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_problem', to='problembank.problemgroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='chat_room',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='اتاق قرار'),
        ),
    ]
