# Generated by Django 3.2.3 on 2022-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game2', '0003_auto_20220826_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='coin',
            field=models.IntegerField(default=700, verbose_name='پول'),
        ),
    ]
