# Generated by Django 3.2.3 on 2022-08-26 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problembank', '0001_initial'),
        ('Game2', '0004_auto_20220827_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.AddField(
            model_name='team',
            name='group_problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='team', to='problembank.ProblemGroup'),
        ),
        migrations.AlterField(
            model_name='box',
            name='open_cost',
            field=models.IntegerField(default=5000, verbose_name='هزینه باز کردن جعبه'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
    ]
