# Generated by Django 3.2.3 on 2022-08-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game2', '0007_auto_20220827_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='max_time_to_play',
            field=models.FloatField(default=14400),
        ),
    ]
