# Generated by Django 3.1 on 2021-08-25 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('finish_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('maximum_number_of_received_problem', models.IntegerField(default=2, verbose_name='حداکثر تعداد سوالاتی که بازیکن در یک لحظه می\u200cتواند داشته باشد')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('games', models.ManyToManyField(blank=True, to='Game.Game', verbose_name='آزمون(ها)')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('SHORT_ANSWER', 'Short Answer'), ('DESCRIPTIVE', 'Descriptive'), ('COMET', 'Comet'), ('GROUP', 'Group')], default='DESCRIPTIVE', max_length=20, verbose_name='نوع')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20, verbose_name='سختی')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه\u200cی دریافت')),
                ('reward', models.IntegerField(default=0, verbose_name='پاداش حل\u200cکردن')),
                ('text', models.TextField(verbose_name='متن')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ (اختیاری)')),
                ('games', models.ManyToManyField(to='Game.Game', verbose_name='بازی\u200c(ها)')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Game.subject', verbose_name='موضوع')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بازیکن')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.game', verbose_name='بازی')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربر(ان)')),
            ],
        ),
        migrations.CreateModel(
            name='BaseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('DELIVERED', 'Delivered'), ('SCORED', 'Scored')], default='RECEIVED', max_length=10, verbose_name='وضعیت')),
                ('mark', models.IntegerField(default=-1, verbose_name='نمره')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.player', verbose_name='بازیکن')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('baseanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Game.baseanswer')),
                ('text_answer', models.TextField(verbose_name='پاسخ متنی')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='game-answers/', verbose_name='فایل پاسخ')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem', to='Game.problem', verbose_name='مسئله')),
            ],
            bases=('Game.baseanswer',),
        ),
    ]
