# Generated by Django 3.2.3 on 2021-09-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckableObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='GameProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=0, verbose_name='سکه')),
                ('blue_toot', models.IntegerField(default=0, verbose_name='توت آبی')),
                ('red_toot', models.IntegerField(default=0, verbose_name='توت قرمز')),
                ('black_toot', models.IntegerField(default=0, verbose_name='توت سیاه')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='پیام')),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, null=True, upload_to='game/'))),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نسبی')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCheckableObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='آیا بازیکن، شی را بررسی کرده؟')),
                ('checkable_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.checkableobject', verbose_name='شی')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='black_toot',
            field=models.IntegerField(default=0, verbose_name='توت سیاه'),
        ),
        migrations.AddField(
            model_name='player',
            name='blue_toot',
            field=models.IntegerField(default=0, verbose_name='توت آبی'),
        ),
        migrations.AddField(
            model_name='player',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='سکه'),
        ),
        migrations.AddField(
            model_name='player',
            name='has_answered_first_problem',
            field=models.BooleanField(default=False, verbose_name='آیا سوال اولیه رو پاسخ داده است؟'),
        ),
        migrations.AddField(
            model_name='player',
            name='has_found_famous_person1',
            field=models.BooleanField(default=False, verbose_name='آیا نفر اول تو تالار مشاهیر رو یافته\u200cاند؟'),
        ),
        migrations.AddField(
            model_name='player',
            name='has_found_famous_person2',
            field=models.BooleanField(default=False, verbose_name='آیا نفر دوم تو تالار مشاهیر رو یافته\u200cاند؟'),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_free_check',
            field=models.IntegerField(default=0, verbose_name='تعداد بارهایی که بازیکن می\u200cتواند به صورت رایگان عمل چک\u200cکردن را انجام دهد'),
        ),
        migrations.AddField(
            model_name='player',
            name='red_toot',
            field=models.IntegerField(default=0, verbose_name='توت قرمز'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='playercheckableobject',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='messages',
            field=models.ManyToManyField(to='Game.Message', verbose_name='پیام\u200cها'),
        ),
        migrations.AddField(
            model_name='gameproblem',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.merchandise', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='gameproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problembank.problem', verbose_name='مسئله از بانک سوال:'),
        ),
        migrations.AddField(
            model_name='checkableobject',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.merchandise', verbose_name='کالا'),
        ),
    ]
