# Generated by Django 3.1 on 2021-08-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maximum_number_of_received_problem_per_subject',
            field=models.IntegerField(default=6, verbose_name='حداکثر تعداد سوالاتی که یک بازیکن در کل مسابقه از یک مبحث می\u200cتواند داشته باشد'),
        ),
        migrations.AlterField(
            model_name='baseanswer',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DELIVERED', 'Delivered'), ('SCORED', 'Scored')], default='RECEIVED', max_length=10, verbose_name='وضعیت'),
        ),
    ]
