# Generated by Django 3.1 on 2021-08-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='game',
        ),
        migrations.AddField(
            model_name='subject',
            name='games',
            field=models.ManyToManyField(blank=True, to='Game.Game', verbose_name='آزمون(ها)'),
        ),
        migrations.AlterField(
            model_name='baseanswer',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DELIVERED', 'Delivered'), ('SCORED', 'Scored')], default='RECEIVED', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='cometproblem',
            name='problems',
            field=models.ManyToManyField(to='Game.Problem', verbose_name='مسئله(ها)'),
        ),
    ]
