# Generated by Django 3.2.3 on 2021-09-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
        ('Game', '0002_auto_20210909_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkableobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='TootenkhAmoo/checkable_objects/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='player',
            name='has_find_TABOOT',
            field=models.BooleanField(default=False, verbose_name='آیا تابوت توتنخ\u200cعامو رو پیدا کرده\u200cاند؟'),
        ),
        migrations.AlterField(
            model_name='gameproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problembank.problem', verbose_name='مسئله از بانک مسئله'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='TootenkhAmoo/messages/', verbose_name='تصویر'),
        ),
    ]
