# Generated by Django 3.1 on 2021-08-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20210824_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام تیم'),
        ),
        migrations.AlterField(
            model_name='baseanswer',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DELIVERED', 'Delivered'), ('SCORED', 'Scored')], default='RECEIVED', max_length=10, verbose_name='وضعیت'),
        ),
    ]
