# Generated by Django 3.2.3 on 2021-09-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_alter_baseanswer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseanswer',
            name='status',
        ),
    ]
