# Generated by Django 3.2.3 on 2021-09-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_alter_notification_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='famous_person/checkable_objects/', verbose_name='تصویر')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='has_found_famous_person1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='has_found_famous_person2',
        ),
        migrations.CreateModel(
            name='PlayerFamousPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='آیا بازیکن، شی را بررسی کرده؟')),
                ('famous_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.famousperson', verbose_name='شخص معروف')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.player', verbose_name='بازیکن')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_merchandise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_merchandise', to='Game.merchandise', verbose_name='کالایی خریداری\u200cشده')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to='Game.player', verbose_name='خریدار')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='Game.player', verbose_name='فروشنده')),
                ('sold_merchandise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_merchandise', to='Game.merchandise', verbose_name='کالایی فروخته\u200cشده')),
            ],
        ),
        migrations.AddField(
            model_name='gameproblem',
            name='famous_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Game.famousperson', verbose_name='شخص معروف'),
        ),
    ]
