# Generated by Django 3.2.3 on 2021-09-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
        ('Game', '0006_auto_20210909_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameproblem',
            old_name='merchandise',
            new_name='reward_merchandise',
        ),
        migrations.RemoveField(
            model_name='gameproblem',
            name='problem',
        ),
        migrations.AddField(
            model_name='gameproblem',
            name='problem_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submit_answer', to='problembank.problemgroup', verbose_name='مسئله از بانک مسئله'),
        ),
        migrations.AddField(
            model_name='player',
            name='famous_persons',
            field=models.ManyToManyField(to='Game.FamousPerson', verbose_name='اشخاص معروف'),
        ),
        migrations.DeleteModel(
            name='PlayerFamousPerson',
        ),
    ]
