# Generated by Django 3.2.3 on 2021-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_auto_20210909_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='checkable_objects',
            field=models.ManyToManyField(blank=True, to='Game.CheckableObject', verbose_name='اشیا'),
        ),
        migrations.AlterField(
            model_name='player',
            name='famous_persons',
            field=models.ManyToManyField(blank=True, to='Game.FamousPerson', verbose_name='اشخاص معروف'),
        ),
        migrations.DeleteModel(
            name='PlayerCheckableObject',
        ),
    ]
