# Generated by Django 3.2.3 on 2021-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_auto_20210910_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
