# Generated by Django 3.2.3 on 2021-09-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_alter_player_name'),
        ('Game', '0010_auto_20210910_0640'),
    ]

    operations = [
    ]
