# Generated by Django 3.2.3 on 2021-09-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('ShortAnswerProblem', 'Shortanswerproblem'), ('DescriptiveProblem', 'Descriptiveproblem')], default='DescriptiveProblem', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=100, verbose_name='عنوان'),
        ),
    ]
