# Generated by Django 3.2.3 on 2021-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
