# Generated by Django 3.2.3 on 2021-09-07 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochecksubmit',
            name='problem_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autochecksubmit', to='problembank.problemgroup', verbose_name='دسته مسئله'),
        ),
        migrations.AddField(
            model_name='judgeablesubmit',
            name='problem_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgeablesubmit', to='problembank.problemgroup', verbose_name='دسته مسئله'),
        ),
    ]
