# Generated by Django 3.2.3 on 2021-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproblem',
            name='suitable_for_over',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eight'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth')], default=1, verbose_name='پایین ترین پایه مناسب'),
        ),
        migrations.AlterField(
            model_name='baseproblem',
            name='suitable_for_under',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eight'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth')], default=12, verbose_name='بالاترین پایه مناسب'),
        ),
    ]
