# Generated by Django 3.2.3 on 2021-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0002_auto_20210907_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mentors',
            field=models.ManyToManyField(related_name='editable_events', to='problembank.BankAccount', verbose_name='همیار(ها)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prticipants',
            field=models.ManyToManyField(related_name='participated_events', to='problembank.BankAccount', verbose_name='بیننده(ها)'),
        ),
        migrations.AlterField(
            model_name='problemgroup',
            name='problems',
            field=models.ManyToManyField(related_name='groups', to='problembank.Problem', verbose_name='مسئله(ها)'),
        ),
    ]
