# Generated by Django 3.2.3 on 2021-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0002_alter_bankaccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeablesubmit',
            name='text_tmp1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgeablesubmit',
            name='text_tmp2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
