# Generated by Django 3.2.3 on 2021-09-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0002_auto_20210905_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptiveanswer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='uploadfileanswer',
            name='type',
        ),
        migrations.AddField(
            model_name='descriptiveanswer',
            name='answer_type',
            field=models.CharField(choices=[('ShortAnswer', 'Shortanswer'), ('DescriptiveAnswer', 'Descriptiveanswer')], default='DescriptiveAnswer', max_length=20, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('ShortAnswerProblem', 'Shortanswerproblem'), ('DescriptiveProblem', 'Descriptiveproblem')], default='DescriptiveProblem', max_length=20, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='answer_type',
            field=models.CharField(choices=[('ShortAnswer', 'Shortanswer'), ('DescriptiveAnswer', 'Descriptiveanswer')], default='DescriptiveAnswer', max_length=20, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='uploadfileanswer',
            name='answer_type',
            field=models.CharField(choices=[('ShortAnswer', 'Shortanswer'), ('DescriptiveAnswer', 'Descriptiveanswer')], default='DescriptiveAnswer', max_length=20, verbose_name='نوع'),
        ),
    ]
