# Generated by Django 3.2.3 on 2021-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0003_auto_20210906_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('ShortAnswerProblem', 'Shortanswerproblem'), ('DescriptiveProblem', 'Descriptiveproblem'), ('Problem', 'Problem')], default='DescriptiveProblem', max_length=20, verbose_name='نوع'),
        ),
    ]
