# Generated by Django 3.2.3 on 2021-09-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0004_auto_20210911_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='prticipants',
            new_name='participants',
        ),
    ]
