# Generated by Django 3.2.3 on 2021-09-06 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0005_alter_descriptiveproblem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='last_change_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان انتشار'),
        ),
    ]
