# Generated by Django 3.2.3 on 2022-01-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0005_rename_prticipants_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mentor_password',
            field=models.CharField(default='04tja5YV', max_length=30, verbose_name='رمز منتور'),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_password',
            field=models.CharField(default='M4IgJXmH', max_length=30, verbose_name='رمز شرکت کننده'),
        ),
    ]
