# Generated by Django 3.2.3 on 2022-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0006_auto_20220102_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture_link',
            field=models.CharField(default='https://problembank.ir/logo.png', max_length=200, verbose_name='عکس'),
        ),
    ]
