# Generated by Django 3.2.3 on 2022-01-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0007_event_picture_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='picture_link',
            new_name='image_link',
        ),
    ]
