# Generated by Django 3.2.3 on 2022-09-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0008_rename_picture_link_event_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problem-files/', verbose_name='فایل صورت مسئله'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='answer_file',
            field=models.FileField(max_length=4000, upload_to='answer-files/'),
        ),
    ]
